/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.waverider_project.app_tables;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JobRunSchedule generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`JobRunSchedule`")
public class JobRunSchedule implements Serializable {

    private Integer id;
    private String jobName;
    private LocalDateTime scheduleRunTime;
    private String scheduleDays;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`Id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`JobName`", nullable = false, length = 100)
    public String getJobName() {
        return this.jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    @Column(name = "`ScheduleRunTime`", nullable = false)
    public LocalDateTime getScheduleRunTime() {
        return this.scheduleRunTime;
    }

    public void setScheduleRunTime(LocalDateTime scheduleRunTime) {
        this.scheduleRunTime = scheduleRunTime;
    }

    @Column(name = "`ScheduleDays`", nullable = false, length = 100)
    public String getScheduleDays() {
        return this.scheduleDays;
    }

    public void setScheduleDays(String scheduleDays) {
        this.scheduleDays = scheduleDays;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof JobRunSchedule)) return false;
        final JobRunSchedule jobRunSchedule = (JobRunSchedule) o;
        return Objects.equals(getId(), jobRunSchedule.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}