/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.waverider_project.app_tables;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransactionLog generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TransactionLog`")
public class TransactionLog implements Serializable {

    private Integer id;
    private String projectName;
    private String transactionId;
    private String transactionName;
    private String parentTransactionId;
    private String parentTransactionName;
    private String hostName;
    private String sourceSystem;
    private String messageType;
    private String messageCode;
    private String messageText;
    private LocalDateTime createDate;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`Id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`ProjectName`", nullable = true, length = 100)
    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    @Column(name = "`TransactionID`", nullable = false, length = 30)
    public String getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    @Column(name = "`TransactionName`", nullable = false, length = 100)
    public String getTransactionName() {
        return this.transactionName;
    }

    public void setTransactionName(String transactionName) {
        this.transactionName = transactionName;
    }

    @Column(name = "`ParentTransactionID`", nullable = true, length = 30)
    public String getParentTransactionId() {
        return this.parentTransactionId;
    }

    public void setParentTransactionId(String parentTransactionId) {
        this.parentTransactionId = parentTransactionId;
    }

    @Column(name = "`ParentTransactionName`", nullable = true, length = 100)
    public String getParentTransactionName() {
        return this.parentTransactionName;
    }

    public void setParentTransactionName(String parentTransactionName) {
        this.parentTransactionName = parentTransactionName;
    }

    @Column(name = "`HostName`", nullable = true, length = 100)
    public String getHostName() {
        return this.hostName;
    }

    public void setHostName(String hostName) {
        this.hostName = hostName;
    }

    @Column(name = "`SourceSystem`", nullable = false, length = 30)
    public String getSourceSystem() {
        return this.sourceSystem;
    }

    public void setSourceSystem(String sourceSystem) {
        this.sourceSystem = sourceSystem;
    }

    @Column(name = "`MessageType`", nullable = false, length = 3)
    public String getMessageType() {
        return this.messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    @Column(name = "`MessageCode`", nullable = false, length = 10)
    public String getMessageCode() {
        return this.messageCode;
    }

    public void setMessageCode(String messageCode) {
        this.messageCode = messageCode;
    }

    @Column(name = "`MessageText`", nullable = true, length = 100)
    public String getMessageText() {
        return this.messageText;
    }

    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }

    @Column(name = "`CreateDate`", nullable = true)
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TransactionLog)) return false;
        final TransactionLog transactionLog = (TransactionLog) o;
        return Objects.equals(getId(), transactionLog.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}