/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.waverider_project.app_tables.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.waverider_project.app_tables.models.query.*;

public interface App_TablesQueryExecutorService {

    Page<YettoruncountResponse> executeYettoruncount(Pageable pageable);

    void exportYettoruncount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<NofilecountResponse> executeNofilecount(Pageable pageable);

    void exportNofilecount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<StarterrorcountResponse> executeStarterrorcount(Pageable pageable);

    void exportStarterrorcount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<FailcountResponse> executeFailcount(Pageable pageable);

    void exportFailcount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<CurrentdateResponse> executeCurrentdate(Pageable pageable);

    void exportCurrentdate(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<PasscountResponse> executePasscount(Pageable pageable);

    void exportPasscount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<JobcountResponse> executeJobcount(Pageable pageable);

    void exportJobcount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<CurrentDatetimeResponse> executeCurrent_datetime(Pageable pageable);

    void exportCurrent_datetime(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}