/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.waverider_project.app_tables.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.waverider_project.app_tables.models.query.*;

@Service
public class App_TablesQueryExecutorServiceImpl implements App_TablesQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(App_TablesQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("App_TablesWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "App_TablesTransactionManager", readOnly = true)
    @Override
    public Page<YettoruncountResponse> executeYettoruncount(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("yettoruncount", params, YettoruncountResponse.class, pageable);
    }

    @Transactional(value = "App_TablesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportYettoruncount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<YettoruncountResponse> queryInput = new QueryProcedureInput<>("yettoruncount", params, YettoruncountResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "App_TablesTransactionManager", readOnly = true)
    @Override
    public Page<NofilecountResponse> executeNofilecount(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("Nofilecount", params, NofilecountResponse.class, pageable);
    }

    @Transactional(value = "App_TablesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportNofilecount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<NofilecountResponse> queryInput = new QueryProcedureInput<>("Nofilecount", params, NofilecountResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "App_TablesTransactionManager", readOnly = true)
    @Override
    public Page<StarterrorcountResponse> executeStarterrorcount(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("starterrorcount", params, StarterrorcountResponse.class, pageable);
    }

    @Transactional(value = "App_TablesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportStarterrorcount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<StarterrorcountResponse> queryInput = new QueryProcedureInput<>("starterrorcount", params, StarterrorcountResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "App_TablesTransactionManager", readOnly = true)
    @Override
    public Page<FailcountResponse> executeFailcount(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("Failcount", params, FailcountResponse.class, pageable);
    }

    @Transactional(value = "App_TablesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportFailcount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<FailcountResponse> queryInput = new QueryProcedureInput<>("Failcount", params, FailcountResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "App_TablesTransactionManager", readOnly = true)
    @Override
    public Page<CurrentdateResponse> executeCurrentdate(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("currentdate", params, CurrentdateResponse.class, pageable);
    }

    @Transactional(value = "App_TablesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportCurrentdate(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<CurrentdateResponse> queryInput = new QueryProcedureInput<>("currentdate", params, CurrentdateResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "App_TablesTransactionManager", readOnly = true)
    @Override
    public Page<PasscountResponse> executePasscount(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("Passcount", params, PasscountResponse.class, pageable);
    }

    @Transactional(value = "App_TablesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportPasscount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<PasscountResponse> queryInput = new QueryProcedureInput<>("Passcount", params, PasscountResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "App_TablesTransactionManager", readOnly = true)
    @Override
    public Page<JobcountResponse> executeJobcount(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("Jobcount", params, JobcountResponse.class, pageable);
    }

    @Transactional(value = "App_TablesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportJobcount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<JobcountResponse> queryInput = new QueryProcedureInput<>("Jobcount", params, JobcountResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "App_TablesTransactionManager", readOnly = true)
    @Override
    public Page<CurrentDatetimeResponse> executeCurrent_datetime(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("current_datetime", params, CurrentDatetimeResponse.class, pageable);
    }

    @Transactional(value = "App_TablesTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportCurrent_datetime(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<CurrentDatetimeResponse> queryInput = new QueryProcedureInput<>("current_datetime", params, CurrentDatetimeResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}