/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.waverider_project.app_tables.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CurrentdateResponse implements Serializable {


    @ColumnAlias("Id")
    private Integer id;

    @ColumnAlias("JobName")
    private String jobName;

    @ColumnAlias("ScheduleRunTime")
    private LocalDateTime scheduleRunTime;

    @ColumnAlias("ScheduleDays")
    private String scheduleDays;

    @ColumnAlias("ActualRunTime")
    private LocalDateTime actualRunTime;

    @ColumnAlias("Status")
    private String status;

    @ColumnAlias("Remarks")
    private String remarks;

    @ColumnAlias("BatchMonitor")
    private String batchMonitor;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getJobName() {
        return this.jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public LocalDateTime getScheduleRunTime() {
        return this.scheduleRunTime;
    }

    public void setScheduleRunTime(LocalDateTime scheduleRunTime) {
        this.scheduleRunTime = scheduleRunTime;
    }

    public String getScheduleDays() {
        return this.scheduleDays;
    }

    public void setScheduleDays(String scheduleDays) {
        this.scheduleDays = scheduleDays;
    }

    public LocalDateTime getActualRunTime() {
        return this.actualRunTime;
    }

    public void setActualRunTime(LocalDateTime actualRunTime) {
        this.actualRunTime = actualRunTime;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getBatchMonitor() {
        return this.batchMonitor;
    }

    public void setBatchMonitor(String batchMonitor) {
        this.batchMonitor = batchMonitor;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CurrentdateResponse)) return false;
        final CurrentdateResponse currentdateResponse = (CurrentdateResponse) o;
        return Objects.equals(getId(), currentdateResponse.getId()) &&
                Objects.equals(getJobName(), currentdateResponse.getJobName()) &&
                Objects.equals(getScheduleRunTime(), currentdateResponse.getScheduleRunTime()) &&
                Objects.equals(getScheduleDays(), currentdateResponse.getScheduleDays()) &&
                Objects.equals(getActualRunTime(), currentdateResponse.getActualRunTime()) &&
                Objects.equals(getStatus(), currentdateResponse.getStatus()) &&
                Objects.equals(getRemarks(), currentdateResponse.getRemarks()) &&
                Objects.equals(getBatchMonitor(), currentdateResponse.getBatchMonitor());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getJobName(),
                getScheduleRunTime(),
                getScheduleDays(),
                getActualRunTime(),
                getStatus(),
                getRemarks(),
                getBatchMonitor());
    }
}