/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.waverider_project.app_tables.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CurrentDatetimeResponse implements Serializable {


    @ColumnAlias("CONCAT(DATE_FORMAT(CURRENT_DATE(),'%W, %b %d %Y,'),' ',DATE_FORMAT(CONVERT_TZ(CURRENT_TIME(),'+00:00','+05:30'),'%T'),' ','IST')")
    private String concat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__;

    public String getConcat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__() {
        return this.concat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__;
    }

    public void setConcat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__(String concat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__) {
        this.concat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__ = concat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CurrentDatetimeResponse)) return false;
        final CurrentDatetimeResponse currentDatetimeResponse = (CurrentDatetimeResponse) o;
        return Objects.equals(getConcat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__(), currentDatetimeResponse.getConcat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getConcat_dateFormat_currentDate_____w__b_d_y_______dateFormat_convertTz_currentTime_____00_00____05_30_____t_______ist__());
    }
}