/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.waverider_project.app_tables.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class YettoruncountResponse implements Serializable {


    @ColumnAlias("count(*)")
    private Long count___;

    public Long getCount___() {
        return this.count___;
    }

    public void setCount___(Long count___) {
        this.count___ = count___;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof YettoruncountResponse)) return false;
        final YettoruncountResponse yettoruncountResponse = (YettoruncountResponse) o;
        return Objects.equals(getCount___(), yettoruncountResponse.getCount___());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCount___());
    }
}